name: updater-release
on:
  release:
    types: [created]

jobs:
  build-release:
    name: build-release
    strategy:
      matrix:
        build: [linux-x86_64,macos-x86_64,windows-x86_64-msvc,windows-i686-msvc]
        include:
          - build: linux-x86_64
            os: ubuntu-latest
            rust: stable-x86_64-unknown-linux-gnu
            target: x86_64-unknown-linux-gnu
          - build: macos-x86_64
            os: macos-latest
            rust: stable-x86_64-apple-darwin
            target: x86_64-apple-darwin
          - build: windows-x86_64-msvc
            os: windows-latest
            rust: stable-x86_64-pc-windows-msvc
            target: x86_64-pc-windows-msvc
          - build: windows-i686-msvc
            os: windows-latest
            rust: stable-i686-pc-windows-msvc
            target: i686-pc-windows-msvc

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: install rustup
        run: |
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs > rustup-init.sh
          sh rustup-init.sh -y --default-toolchain ${{ matrix.rust }}
          rustup target add ${{ matrix.target }}
        
      - name: install dependencies
        run: |
          sudo apt update
          sudo apt install libx11-dev libpango1.0-dev libxkbcommon-dev libxkbcommon-x11-dev libgtk-3-dev gcc-multilib
        if: contains(matrix.os, 'ubuntu')
      
      # Run build
      - name: Build release druid features
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --target=${{ matrix.target }}

      - name: Build archive druid features
        shell: bash
        run: |
          staging="updater_${{ matrix.build }}_${{ github.event.release.tag_name }}"
          mkdir -p "$staging"
          if [ "${{ matrix.os }}" = "windows-latest" ]; then
            cp target/${{matrix.target}}/release/updater.exe "$staging/"
            7z a "$staging.zip" "$staging"
            echo "ASSET=$staging.zip" >> $GITHUB_ENV
          else
            cp target/${{matrix.target}}/release/updater "$staging/"
            tar czf "$staging.tar.gz" "$staging"
            echo "ASSET=$staging.tar.gz" >> $GITHUB_ENV
          fi

      - name: Upload Release Asset druid features
        if: github.event_name == 'release'
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ${{ env.ASSET }}
          asset_name: ${{ env.ASSET }}
          asset_content_type: application/octet-stream

      # Run build
      - name: Build release no features
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --no-default-features --target=${{ matrix.target }}

      - name: Build archive no features
        shell: bash
        run: |
          staging="updater_cli_${{ matrix.build }}_${{ github.event.release.tag_name }}"
          mkdir -p "$staging"
          if [ "${{ matrix.os }}" = "windows-latest" ]; then
            cp target/${{matrix.target}}/release/updater.exe "$staging/"
            7z a "$staging.zip" "$staging"
            echo "ASSET=$staging.zip" >> $GITHUB_ENV
          else
            cp target/${{matrix.target}}/release/updater "$staging/"
            tar czf "$staging.tar.gz" "$staging"
            echo "ASSET=$staging.tar.gz" >> $GITHUB_ENV
          fi

      - name: Upload Release Asset no features
        if: github.event_name == 'release'
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ${{ env.ASSET }}
          asset_name: ${{ env.ASSET }}
          asset_content_type: application/octet-stream

